### ISSUE TITLE
Development ?

### ISSUE THREAD

**Issue by IvanDelsinne** [fiftysoft/form-validation#1]
Hello, I wanted to know if you'd be open to continue develop this library, provided that I give out some contributions.

First thing for me would be to add french translations, and maybe a few other filters, but I wanted to know if you'd be open for pull-requests, or if I should directly fork it and focus on developing it myself

**Comment by fiftysoft** [comment]
Hello @IvanDelsinne ,
pull requests its open there is no limit you can do what you want 👍
